production:
  branch: "production"
  deploy_to: "/home/palava/www/portal-production"
  post_deploy_script: config/post_deploy.sh
  post_setup_script:  config/post_deploy.sh
  domain: "palava@176.28.9.212"
  repository: "/home/git/portal.git"

playground:
  branch: "playground"
  deploy_to: "/home/palava/www/portal-playground"
  post_deploy_script: config/post_deploy.sh
  post_setup_script:  config/post_deploy.sh
  domain: "palava@176.28.9.212"
  repository: "/home/git/portal.git"
